name: reminders
description: This dart package gives access to ios reminders. Reminders are sorted into lists with one list being the default. This package gives read and delete access.
version: 0.0.2
homepage: https://github.com/berkobob/Reminders

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      ios:
        pluginClass: RemindersPlugin
